module.exports = {
    COLLECTION: {
        DIRECTORY: 'MediaDirectory',
        MEDIA: 'Media',
        UPLOAD: 'MediaUpload',
    },
    ERRORS: {
        DIRECTORY: 'directory is a required parameter.',
        DUPLICATE_DIRECTORY: 'directory already exists',
        FILE: 'filename is a required parameter',
        FILE_DELETE: 'Unable to delete file',
        PERMISSION: 'Permission denied',
    },
    STATUS: {
        COMPLETE: 'complete',
        QUEUED: 'queued',
        UPLOADING: 'uploading',
    },
    TYPE: {
        AUDIO: ['MP3', 'OGG', 'WAV'],
        IMAGE: ['PNG', 'SVG', 'GIF', 'JPG', 'JPEG'],
        PDF: ['PDF'],
        VIDEO: [
            'WEBM',
            'MPG',
            'MP2',
            'MPEG',
            'MPE',
            'MPV',
            'OGG',
            'MP4',
            'M4P',
            'M4V',
            'AVI',
            'WMV',
            'MOV',
            'QT',
            'FLV',
            'SWF',
            'AVCHD',
        ],
    },
};
