module.exports = {
    CACHE: 90 * 1000,
    CRON_SETTING: 'publish-frequency',
    STATUS: {
        TRASH: 'TRASH',
        DRAFT: 'DRAFT',
        PUBLISHED: 'PUBLISHED',
    },
    ERRORS: {
        PERMISSION: 'Permission denied',
    },
    CHANGES: {
        CREATED: 'CREATED',
        REVISED: 'REVISED',
        CREATED_BRANCH: 'CREATED_BRANCH',
        DELETED_BRANCH: 'DELETED_BRANCH',
        SLUG_CHANGED: 'SLUG_CHANGED',
        SET_REVISION: 'SET_REVISION',
        SET_ACL: 'SET_ACL',
        SET_STATUS: 'SET_STATUS',
        PUBLISHED: 'PUBLISHED',
        UNPUBLISHED: 'UNPUBLISHED',
        SCHEDULE: 'SCHEDULE',
        UNSCHEDULE: 'UNSCHEDULE',
        SCHEDULED_PUBLISH: 'SCHEDULED_PUBLISH',
        SCHEDULED_UNPUBLISH: 'SCHEDULED_UNPUBLISH',
        TRASHED: 'TRASHED',
        DELETED: 'DELETED',
        RESTORED: 'RESTORED',
    },
};
