const PLUGIN = require('./meta');
const PLUGIN_ROUTES = require('./routes');
const PLUGIN_BLUEPRINTS = require('./blueprints');
const resetRequest = require('./utils/resetRequest');
const resetPassword = require('./utils/resetPassword');

const TokenSchema = {
    value: { type: 'String' },
    expireAt: { type: 'Date' },
    user: { type: 'Pointer', targetClass: '_User' },
};

Actinium.Plugin.register(PLUGIN, true);

Actinium.Hook.register('activate', async ({ ID }) => {
    if (ID !== PLUGIN.ID) {
        return;
    }

    const actions = {
        addField: false,
        create: false,
        delete: false,
        retrieve: false,
        update: false,
    };

    Object.keys(actions).forEach(action =>
        Actinium.Capability.register(`Token.${action}`),
    );

    Actinium.Collection.register('Token', actions, TokenSchema);
});

Actinium.Hook.register('blueprint-defaults', blueprints => {
    if (Actinium.Plugin.isActive(PLUGIN.ID)) {
        PLUGIN_BLUEPRINTS.forEach(item => blueprints.push(item));
    }
});

Actinium.Hook.register('route-defaults', routes => {
    if (Actinium.Plugin.isActive(PLUGIN.ID)) {
        PLUGIN_ROUTES.forEach(item => routes.push(item));
    }
});


/**
 * @api {Cloud} password-reset password-reset
 * @apiVersion 3.1.1
 * @apiGroup Cloud
 * @apiName password-reset
 * @apiDescription Update a user password.
 * @apiParam {String} token The token generated by password-reset-request.
 * @apiParam {String} password The new password.
 * @apiExample Example Usage:
Actinium.Cloud.run('password-reset', { token: 'Ox3Nlojb', password: 'my.New-P455w0rd!' });
 */
Actinium.Cloud.define(PLUGIN.ID, 'password-reset', resetPassword);

/**
 * @api {Cloud} password-reset-request password-reset-request
 * @apiVersion 3.1.1
 * @apiGroup Cloud
 * @apiName password-reset-request
 * @apiDescription Send the password reset request email.
 * @apiParam {String} email The email address associated with the user account you wish to reset.
 * @apiExample Example Usage:
Actinium.Cloud.run('password-reset-request', { email: 'you@email.com' });
 */
Actinium.Cloud.define(PLUGIN.ID, 'password-reset-request', resetRequest);

Actinium.User.resetRequest = email =>
    Actinium.Cloud.run(
        'password-reset-request',
        { email },
        { useMasterKey: true },
    );

Actinium.User.resetPassword = (token, password) =>
    Actinium.Cloud.run('password-reset', { token, password }, { useMasterKey: true });
